# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kstatusnotifieritem': '@latest-kf6'
    'frameworks/sonnet': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/knotifyconfig': '@latest-kf6'

 - 'on': ['Linux', 'FreeBSD']
   'require':
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/purpose': '@latest-kf6'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
 cppcheck-arguments: '--enable=warning,style,performance --inline-suppr --suppress=passedByValue --suppress=nullPointer'
 tests-run-in-parallel: True
